
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jul 30 16:45:58 EDT 2015
//----------------------------------------------------

package data.packages.CONSCIENCIA.SYNTAX;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AS = 65;
  public static final int COMBEGIN = 79;
  public static final int AN = 66;
  public static final int PHILOSOPHICAL_DEFINITION_QUERY_TARGET_0 = 28;
  public static final int READ = 76;
  public static final int DEFINITION_QUERY_PREFIX_0 = 26;
  public static final int ELIPSE = 31;
  public static final int NOTBIT = 35;
  public static final int SUBSEQUENTLY_DISPLAY = 74;
  public static final int NOTEQ = 41;
  public static final int PERIOD = 9;
  public static final int SEMI = 8;
  public static final int EXP = 7;
  public static final int OBJEQUAL = 57;
  public static final int RBRACK = 52;
  public static final int COMMA = 10;
  public static final int RBRACE = 84;
  public static final int DEFINE = 63;
  public static final int RPAREN = 82;
  public static final int SIMULATION_QUERY_TARGET_1 = 30;
  public static final int SIMULATION_QUERY_TARGET_0 = 29;
  public static final int LBRACK = 51;
  public static final int WEIGHT_QUERY_SUFFIX2 = 20;
  public static final int WEIGHT_QUERY_SUFFIX1 = 19;
  public static final int EQV = 56;
  public static final int WEIGHT_QUERY_SUFFIX0 = 18;
  public static final int INTEGER = 91;
  public static final int DOUBLE = 92;
  public static final int LBRACE = 83;
  public static final int LPAREN = 81;
  public static final int DISPLAY = 73;
  public static final int TRUE_QUERY_SELF_WEIGHT_DECLARATION_SUFFIX = 25;
  public static final int FALSE = 87;
  public static final int NOT = 44;
  public static final int NIL = 85;
  public static final int READINT = 77;
  public static final int THEN = 70;
  public static final int PROC = 59;
  public static final int MODULATE = 15;
  public static final int LVECTORBRACK = 53;
  public static final int MUL = 4;
  public static final int MOD = 6;
  public static final int SIMULATION_QUERY_PREFIX_0 = 27;
  public static final int LOE = 39;
  public static final int TRUE_QUERY_SELF_DECLARATION_SUFFIX1 = 23;
  public static final int CDR = 48;
  public static final int TRUE_QUERY_SELF_DECLARATION_SUFFIX0 = 22;
  public static final int TRUE = 86;
  public static final int COMEND = 80;
  public static final int TRUE_QUERY_SELF_WEIGHT_DECLARATION_PREFIX = 24;
  public static final int PLUS = 2;
  public static final int PRODUCE = 13;
  public static final int QUOTE = 14;
  public static final int EQUAL = 36;
  public static final int CHAR = 88;
  public static final int ASSIGN = 68;
  public static final int STATE = 64;
  public static final int VISUALLY_DISPLAY = 75;
  public static final int VARIABLE = 90;
  public static final int GREATER = 37;
  public static final int DIV = 5;
  public static final int CONCAT = 45;
  public static final int ELSE = 71;
  public static final int GOE = 40;
  public static final int EOF = 0;
  public static final int A = 67;
  public static final int OUTPUT_SOURCE_PREFIX = 32;
  public static final int COM = 78;
  public static final int MINUS = 3;
  public static final int RVECTORBRACK = 54;
  public static final int OR = 43;
  public static final int PAIRBOOL = 49;
  public static final int error = 1;
  public static final int LESSER = 38;
  public static final int EXPOUND = 16;
  public static final int PAIR = 46;
  public static final int LIST = 50;
  public static final int IF = 69;
  public static final int WEIGHT_QUERY_PREFIX = 17;
  public static final int TRUE_QUERY_SELF_DECLARATION_PREFIX = 21;
  public static final int LAZY = 61;
  public static final int CASE = 72;
  public static final int ORBIT = 34;
  public static final int STRING = 89;
  public static final int SIZE = 55;
  public static final int CAR = 47;
  public static final int SUMMATE = 11;
  public static final int ANDBIT = 33;
  public static final int DIFFER = 12;
  public static final int AND = 42;
  public static final int SUBSTR = 58;
  public static final int LET = 62;
  public static final int CALL = 60;
}
